# HOW TO USE PRETTIER
#
# 1. add following packages
#    prettier eslint-config-prettier eslint-plugin-prettier
# 2. add .eslintrc.yml
# 3. add a following script into package.json
#    "prettier": "prettier --write \"src/**/*.{js,jsx,ts,tsx,css}\"",

extends: prettier
parser: babel-eslint
rules:
  prettier/prettier: error

env:
  mocha: true

plugins:
  - prettier

# stop no-undef warning about global variables.
globals:
  document: true
  window: true
  graphql: true
